apiVersion: v1
data:
  jws-kubeconfig-1o9u7j: eyJhbGciOiJIUzI1NiIsImtpZCI6IjFvOXU3aiJ9..tycq_ITarARnlielVVhFstqyvUyAQx3IfVEC3UDfYxw
  jws-kubeconfig-7zltvs: eyJhbGciOiJIUzI1NiIsImtpZCI6Ijd6bHR2cyJ9..S1x_9fcIGp17mpOcbZCiKJ39Y2wPJXn4UZRlmS5YR04
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVFhPNDFBdFBSYzR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeU1qZ3dOalEwTkRWYUZ3MHpNekV5TWpVd05qUTVORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURFNFoxMUkrYWQzM2h0dldJSEw3MFJicHMxR2VqeVJvczR1QU40Y1NleGt6Ri9TZ01mZjNpVE5pY2wKYzNFcFM3ajRCRUgrOU9CTzlad0N0ckwvUU14WC9TbnBtTkNqeWJiRzVXTExOQkF5Y3BWMEw3UnJOUG9uSGdOMApHWWFnY0lua1BrTHE2My8yMTVMN1pocjJrTnA5aUVMT20xTEt5QVhjYmtEN1RaczZ1UnRNV2d0bnNaOGtTeEdCCkVOc1pqK2wrTjdjUHhJN2J2WUlJMFI4L1NVaDhiQ1ZlZDVXL0J6Zjc5Slp3NVBlL1owZlJ3eTBCdThLNytLeTEKZUNoYXdZTzd5WXZYbUxOejNCSHBoMVErenpNdnJ4RDE4SUZncStqSU9jV2pFTXVsakxheEM5cERQNmdISS9YLwpKY24xelhua21vOFZCQ04yU3p2K3lnZUtQeFAvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUYURXT1ZnckNLMGI2Mk5ad0RrRzlSdnkvRldEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjRGZ3FoRUpUZwpZa2VqZXJHTHBET1IxeElEU3Z0bWdQb21NVVdqdHQrWUpSWm9zdC8vUGtwWjJmRGJLWUVWRlNzcHNoSWQwcWV3Ci9NamozS1NPSlNTN1IrdTZKcWhUbDZVVXZFNndvM2V4N1FOa2NrekdBa2F4T25Fa29QVXUzcVVxZDhRVjM0Z3oKQmVUTUFVSnM2WjRxUis0TEFzdEVKYUZFZTdQTGIwRDJDa1NXbFJnTGUxK0JLTGdxZlhwQXEvcWZvQW9qbFVIeApDVTVjUEp3bmpKQWRyNkVTKzRTR3g2L081dGE1QXA0VGJZZEt3WUdoNWszKzVsd29BT2J5eVFOTU9TaE90aE9VCnd3Uk41Yk9KU1hMcEdQcDRtS2kxQUpzL2JpUUZITDZnVlV5RGQrOWY3RS9Kc0U2Lzd6c2ZMc3pvZTFwZmIvQ04KWTBabnlRcWcyN1BPCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://192.168.1.2:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-28T06:49:52Z"
  name: cluster-info
  namespace: kube-public
