apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
  creationTimestamp: "2023-12-28T06:54:45Z"
  labels:
    jcnr: "true"
  name: ops-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
