apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-28T06:54:45Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: contrail-system-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-system-role
subjects:
- kind: ServiceAccount
  name: contrail-system-serviceaccount
  namespace: contrail-system
