apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"2a71bcb7-0360-4897-ad34-3314ffd4bed6","creationTimestamp":"2023-12-28T06:53:27Z"}'
  creationTimestamp: "2023-12-28T06:53:27Z"
  name: default
spec:
  bpfLogLevel: ""
  floatingIPs: Disabled
  logSeverityScreen: Info
  reportingInterval: 0s
