apiVersion: crd.projectcalico.org/v1
kind: IPAMHandle
metadata:
  annotations:
    projectcalico.org/metadata: '{"creationTimestamp":null}'
  creationTimestamp: "2023-12-28T06:53:29Z"
  name: ipip-tunnel-addr-sharmag-k8s-dpdk-kubelet1-lqqpff.englab.juniper.net
spec:
  block:
    10.244.238.128/26: 1
  deleted: false
  handleID: ipip-tunnel-addr-sharmag-k8s-dpdk-kubelet1-lqqpff.englab.juniper.net
