apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-12-28T06:49:50Z"
  labels:
    kubernetes.io/metadata.name: kube-node-lease
  name: kube-node-lease
spec:
  finalizers:
  - kubernetes
