apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-12-28T06:49:51Z"
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.2
  ports:
  - name: https
    port: 6443
    protocol: TCP
