apiVersion: events.k8s.io/v1
deprecatedCount: 178
deprecatedFirstTimestamp: "2024-01-02T05:30:20Z"
deprecatedLastTimestamp: "2024-01-02T16:30:34Z"
deprecatedSource:
  component: kubelet
  host: minikube
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T05:30:26Z"
  name: k8s-delete-validation-webhook-789d9cf956-slfpz.17a670b24e48db12
  namespace: default
note: 'MountVolume.SetUp failed for volume "ssl-keys" : secret "k8s-delete-validation-webhook-secret"
  not found'
reason: FailedMount
regarding:
  apiVersion: v1
  kind: Pod
  name: k8s-delete-validation-webhook-789d9cf956-slfpz
  namespace: default
  resourceVersion: "864640"
  uid: b68c7b56-0901-4708-8703-659cd8de4484
type: Warning
