apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-01-02T16:14:49Z"
deprecatedLastTimestamp: "2024-01-02T16:14:49Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2024-01-02T16:14:49Z"
  name: katafygio.17a693ddc872f7b9
  namespace: default
note: Scaled up replica set katafygio-797fbcd6bf to 1
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: katafygio
  namespace: default
  resourceVersion: "1190856"
  uid: d71f94ac-73a0-4630-a57c-701d904e3f73
type: Normal
