apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-02T16:14:49Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{katafygio}
  kind: Pod
  name: katafygio-6656b7b878-qgrq8
  namespace: default
  resourceVersion: "1127716"
  uid: b693c5e3-b907-4a0d-b640-f2ce3d245bfe
kind: Event
lastTimestamp: "2024-01-02T16:14:49Z"
message: Stopping container katafygio
metadata:
  creationTimestamp: "2024-01-02T16:14:49Z"
  name: katafygio-6656b7b878-qgrq8.17a693ddb290dddd
  namespace: default
  uid: e21ea380-ac37-4355-b24a-cb8552e1932d
reason: Killing
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: minikube
type: Normal
