apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-01-02T16:14:49Z"
involvedObject:
  apiVersion: apps/v1
  kind: Deployment
  name: katafygio
  namespace: default
  resourceVersion: "1190856"
  uid: d71f94ac-73a0-4630-a57c-701d904e3f73
kind: Event
lastTimestamp: "2024-01-02T16:14:49Z"
message: Scaled up replica set katafygio-797fbcd6bf to 1
metadata:
  creationTimestamp: "2024-01-02T16:14:49Z"
  name: katafygio.17a693ddc872f7b9
  namespace: default
  uid: 309486ec-639b-4b9d-b81e-645ce957047b
reason: ScalingReplicaSet
reportingComponent: ""
reportingInstance: ""
source:
  component: deployment-controller
type: Normal
