apiVersion: v1
count: 77
eventTime: null
firstTimestamp: "2023-12-28T06:54:45Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: kube-crpd-worker-sts-1
  namespace: jcnr
  resourceVersion: "1272"
  uid: 1f256f42-d101-4d5e-8537-5d61754b7bc7
kind: Event
lastTimestamp: "2023-12-28T13:09:55Z"
message: '0/2 nodes are available: 2 node(s) didn''t have free ports for the requested
  pod ports. preemption: 0/2 nodes are available: 2 No preemption victims found for
  incoming pod..'
metadata:
  creationTimestamp: "2023-12-28T06:54:45Z"
  name: kube-crpd-worker-sts-1.17a4ec66e6093f62
  namespace: jcnr
reason: FailedScheduling
reportingComponent: default-scheduler
reportingInstance: ""
source:
  component: default-scheduler
type: Warning
