apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2023-12-28T06:54:45Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    k8s-app: kube-crpd-worker
  name: conf-kube-crpd-worker-sts-0
  namespace: jcnr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: jcnrstorage
  volumeMode: Filesystem
  volumeName: jcnr-pv-volume-1
