apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-12-28T06:54:53Z"
  creationTimestamp: "2023-12-28T06:54:45Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: webhook-service
  namespace: contrail-deploy
subsets:
- addresses:
  - ip: 192.168.1.3
    nodeName: sharmag-k8s-dpdk-kubelet1-lqqpff.englab.juniper.net
    targetRef:
      kind: Pod
      name: contrail-k8s-deployer-67c445564f-vh5w2
      namespace: contrail-deploy
      uid: d09709b6-8831-48c7-a4fd-255420f890e4
  ports:
  - port: 29443
    protocol: TCP
