apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jcnr
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-12-28T06:54:45Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: webhook-service
  namespace: contrail-deploy
spec:
  clusterIP: 10.10.10.99
  clusterIPs:
  - 10.10.10.99
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 29443
  selector:
    app: contrail-k8s-deployer
  sessionAffinity: None
  type: ClusterIP
