apiVersion: v1
data:
  client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIITXO41AtPRc4wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yMzEyMjgwNjQ0NDVaFw0zMzEyMjUwNjQ5NDVaMBUx
    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDE4Z11I+ad33htvWIHL70Rbps1GejyRos4uAN4cSexkzF/SgMff3iTNicl
    c3EpS7j4BEH+9OBO9ZwCtrL/QMxX/SnpmNCjybbG5WLLNBAycpV0L7RrNPonHgN0
    GYagcInkPkLq63/215L7Zhr2kNp9iELOm1LKyAXcbkD7TZs6uRtMWgtnsZ8kSxGB
    ENsZj+l+N7cPxI7bvYII0R8/SUh8bCVed5W/Bzf79JZw5Pe/Z0fRwy0Bu8K7+Ky1
    eChawYO7yYvXmLNz3BHph1Q+zzMvrxD18IFgq+jIOcWjEMuljLaxC9pDP6gHI/X/
    Jcn1zXnkmo8VBCN2Szv+ygeKPxP/AgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTaDWOVgrCK0b62NZwDkG9Rvy/FWDAV
    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQB4FgqhEJTg
    YkejerGLpDOR1xIDSvtmgPomMUWjtt+YJRZost//PkpZ2fDbKYEVFSspshId0qew
    /Mjj3KSOJSS7R+u6JqhTl6UUvE6wo3ex7QNkckzGAkaxOnEkoPUu3qUqd8QV34gz
    BeTMAUJs6Z4qR+4LAstEJaFEe7PLb0D2CkSWlRgLe1+BKLgqfXpAq/qfoAojlUHx
    CU5cPJwnjJAdr6ES+4SGx6/O5ta5Ap4TbYdKwYGh5k3+5lwoAObyyQNMOShOthOU
    wwRN5bOJSXLpGPp4mKi1AJs/biQFHL6gVUyDd+9f7E/JsE6/7zsfLszoe1pfb/CN
    Y0ZnyQqg27PO
    -----END CERTIFICATE-----
  requestheader-allowed-names: '["front-proxy-client"]'
  requestheader-client-ca-file: |
    -----BEGIN CERTIFICATE-----
    MIIDETCCAfmgAwIBAgIIYryo4Pwb3OEwDQYJKoZIhvcNAQELBQAwGTEXMBUGA1UE
    AxMOZnJvbnQtcHJveHktY2EwHhcNMjMxMjI4MDY0NDQ1WhcNMzMxMjI1MDY0OTQ1
    WjAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAOZLjsg/o3G2GnGKK6xedqIsxSKLLF8amdjg/wcb12ioWi3w
    w3/zD35oGD4mWu0ynh5HMkTZ/Zu+jFi6RRa2ACTpq2lYqII3iUqRyEPQsje69C8W
    1cQfZjhSSzbz4ASHFFBpujq4SMcME8mr1ECYHieJRnFFYiLmRdjN08BV6EMx3wws
    ZHfhkQoTZWb5WmP1BraLAHchOOREP5p96fPLGfcEyRqEnSeymUEL6a/l0tpY9bRi
    NEPpMf62cP0bncf6PKXyqI3FHAeBGfkoN3iNALt5MU8GENEqofamXRQCNxzvk+uF
    kpzpgmss150IBy2Dl2EezPLVjvw8l6H1NOU0giUCAwEAAaNdMFswDgYDVR0PAQH/
    BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCcmJ/NUWlNSjXVlJ+2G
    QsknH3a+MBkGA1UdEQQSMBCCDmZyb250LXByb3h5LWNhMA0GCSqGSIb3DQEBCwUA
    A4IBAQCcMd3Rjl3FKXR9SgfxSf/Q5WfCM1fJB/nwgEdGmKBqv2gel74hAYTVdyd0
    +2x7aNzTFPzl27GqNR6KGu3wHK4RCGVjKUsscb/0F+SV5qV8C48Fzja4nzZrPDD7
    UjYW1YDkzrjs1FdRcPIkkzcBxQh5alY2c0Xza4eVwC0Kl8S38xPQMU7z0mXT5VX7
    iWOnOsblQe6p353cUZddQ9Q/gaHTruQT1GwluNc7a6XSZkilmIJhUwj7/Oni8b2N
    57xZ9ilWLl5LyiHRcU/Z0HOpLfFx/o7ePWhSLaTNDCx8MyfagK5/mgaRtfURtbIn
    WGv/D2s21yI0ZwWftAj3LNioRTrh
    -----END CERTIFICATE-----
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-28T06:49:50Z"
  name: extension-apiserver-authentication
  namespace: kube-system
