apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-12-28T06:50:07Z"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
subsets:
- notReadyAddresses:
  - ip: 10.244.186.193
    nodeName: sharmag-k8s-master-lqqpff.englab.juniper.net
    targetRef:
      kind: Pod
      name: coredns-56bc94896d-9j6nw
      namespace: kube-system
      uid: 74c98d5d-3071-4c7f-9e1e-86ba5ff4f82e
  - ip: 10.244.186.194
    nodeName: sharmag-k8s-master-lqqpff.englab.juniper.net
    targetRef:
      kind: Pod
      name: coredns-56bc94896d-wcbh5
      namespace: kube-system
      uid: a56ea941-cd1b-4af8-8a3f-e2b5b04f3d13
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns
    port: 53
    protocol: UDP
  - name: metrics
    port: 9153
    protocol: TCP
