apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-12-28T06:49:53Z"
  name: kube-controller-manager
  namespace: kube-system
spec:
  acquireTime: "2023-12-28T06:49:53.002146Z"
  holderIdentity: sharmag-k8s-master-lqqpff.englab.juniper.net_9aaf4631-74f2-4799-aa8b-7195996065b9
  leaseDurationSeconds: 15
  leaseTransitions: 0
  renewTime: "2023-12-28T13:13:48.321988Z"
