apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 4592b8e4a989dbc5f6f7947144f51d24
    kubernetes.io/config.mirror: 4592b8e4a989dbc5f6f7947144f51d24
    kubernetes.io/config.seen: "2023-12-28T06:49:53.425202251Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2023-12-28T06:49:53Z"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-sharmag-k8s-master-lqqpff.englab.juniper.net
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: sharmag-k8s-master-lqqpff.englab.juniper.net
    uid: 898d04ae-4b0e-4fd7-bc7f-d0b2e25b861f
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: registry.englab.juniper.net/jfrog-repo/hosted_docker_images/kube-scheduler:v1.28.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: sharmag-k8s-master-lqqpff.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
