apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2023-12-28T06:53:10Z"
  labels:
    k8s-app: calico-kube-controllers
  name: calico-kube-controllers
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
